/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jvsprite;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * Integrantes:
 * -Loran Cazares Guadalupe Zeltzin
 * -Mohedano Torres Efrain
 */
public class jfrmSprite extends javax.swing.JFrame {
    URL urlImagen;
    clsSprite objSprite;
    int cont1, cont2, turno;
    int mov, mov2, posIni, posIni2;
    String[] sprite1 = {"/imagenes/1_1.jpeg", "/imagenes/1_2.jpeg", "/imagenes/1_3.jpeg", "/imagenes/1_4.jpeg", "/imagenes/1_5.jpeg"};
    String[] sprite2 = {"/imagenes/2_1.jpeg", "/imagenes/2_2.jpeg", "/imagenes/2_3.jpeg", "/imagenes/2_4.jpeg", "/imagenes/2_5.jpeg"};
    Timer tmrMovimiento = new Timer(500, new ActionListener (){
        public void actionPerformed(ActionEvent e){
            mover();
        }
    });

    /**
     * Creates new form jfrmSprite
     */
    public jfrmSprite() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        //mostrarImagen(jlblLogo, "/imagenes/logo.jpg");
        objSprite = new clsSprite();
        objSprite.crearEtiquetas(jpanObjetos);
        tmrMovimiento.start();
        // Obtengo las columnas
        mov = objSprite.getEtiquetas().get(1).getX();
        mov2 = objSprite.getEtiquetas().get(0).getY();
        // Guardar la posición inicial
        posIni = objSprite.getEtiquetas().get(1).getX();
        posIni2 = objSprite.getEtiquetas().get(0).getY();
        cont1 = 0;
        cont2 = 0;
        turno = 0;
        mostrarImagen(jlblLogo, "/imagenes/logo.jpg");
    }
    public void mover(){
        if (turno == 0) {
            // Label 1:
            if (cont1 == sprite1.length) {
                cont1 = 0;
                mov2 = posIni2;
                turno = 1;
                objSprite.getEtiquetas().get(0).setVisible(false);
                // Evitar tiempo para pasar
                objSprite.getEtiquetas().get(1).setLocation(mov, objSprite.getEtiquetas().get(1).getY());
                mostrarImagen(objSprite.getEtiquetas().get(1), sprite2[cont2]);
                objSprite.getEtiquetas().get(1).setVisible(true);
                mov += 60;
                cont2 += 1;
            }else{
                if (cont1<3 & cont1>0) {
                    mov2 -=15;
                }else{
                    if (cont1!=0)
                        mov2 +=15;
                }
                objSprite.getEtiquetas().get(0).setLocation(objSprite.getEtiquetas().get(0).getX(), mov2);
                mostrarImagen(objSprite.getEtiquetas().get(0), sprite1[cont1]);
                objSprite.getEtiquetas().get(0).setVisible(true);
                cont1 += 1;
            }
        }else{
            // Label 2:
            if ((mov < (this.getWidth() - objSprite.getEtiquetas().get(1).getWidth() - 100))&&(cont2 < sprite2.length)){
                objSprite.getEtiquetas().get(1).setLocation(mov, objSprite.getEtiquetas().get(1).getY());
                mostrarImagen(objSprite.getEtiquetas().get(1), sprite2[cont2]);
                objSprite.getEtiquetas().get(1).setVisible(true);
                mov += 60;
                cont2 += 1;
            }else{
                cont2 = 0;
                turno = 0;
                mov = posIni;
                objSprite.getEtiquetas().get(1).setVisible(false);
            }
        }
    }
    public void mostrarImagen(JLabel imagenLogo, String urlImg){
        urlImagen = this.getClass().getResource(urlImg);
        ImageIcon imgL = new ImageIcon(urlImagen);
        Icon imagen = new ImageIcon(imgL.getImage().getScaledInstance(imagenLogo.getWidth(), imagenLogo.getHeight(), Image.SCALE_DEFAULT));
        imagenLogo.setIcon(imagen);
        this.repaint();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblLogo = new javax.swing.JLabel();
        jpanObjetos = new javax.swing.JPanel();
        jlblNombre1 = new javax.swing.JLabel();
        jlblNombre2 = new javax.swing.JLabel();
        jlblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jpanObjetos.setBackground(new java.awt.Color(255, 255, 255));

        jlblNombre1.setText("-Mohedano Torres Efrain");

        jlblNombre2.setText("-Loran Cazares Guadalupe Zeltzin");

        javax.swing.GroupLayout jpanObjetosLayout = new javax.swing.GroupLayout(jpanObjetos);
        jpanObjetos.setLayout(jpanObjetosLayout);
        jpanObjetosLayout.setHorizontalGroup(
            jpanObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanObjetosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlblNombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jlblNombre2)
                .addGap(25, 25, 25))
        );
        jpanObjetosLayout.setVerticalGroup(
            jpanObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanObjetosLayout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(jpanObjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombre1)
                    .addComponent(jlblNombre2))
                .addGap(32, 32, 32))
        );

        jlblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblTitulo.setText("Práctica con Sprites");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblTitulo)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblTitulo)
                        .addGap(33, 33, 33)))
                .addComponent(jpanObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmSprite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmSprite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmSprite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmSprite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmSprite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblLogo;
    private javax.swing.JLabel jlblNombre1;
    private javax.swing.JLabel jlblNombre2;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JPanel jpanObjetos;
    // End of variables declaration//GEN-END:variables
}
